name: tractorapp
description: tractorapp
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.4.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  retry: ^3.1.2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  responsive_sizer: ^3.3.1
  package_info_plus: ^8.3.0
  flex_color_scheme: ^8.2.0
  connectivity_plus: ^6.1.4
  firebase_messaging: ^15.2.5
  overlay_support: ^2.1.0
  fast_cached_network_image: ^1.3.3+5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.1.0
  pinput: ^5.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/data/animations/
    - assets/language/
